### ISSUE TITLE
Boots into recovery after flashing

### ISSUE THREAD

**Issue by steveharman** [penglezos/raphael#2]
Hi!  

Firstly a big thank you for doing this for the raphael - I'm excited to try it.

Sadly though I always seem to end up in TWRP (recovery) after flashing the LineageOS ROM

- Mi9T Pro 
- unlocked bootloader
- fresh fastboot-flash of the latest MIUI12.5 global using the Xiaomi Flash tool

The readme states to wipe "Data/Cache/System/Vendor" - is that the case?  I don't think I usually wipe all of those but I could be wrong.  Also is it a requirement to flash "latest Android 11 firmware according to your region" from TWRP before applying the Lineage ROM - or is my fastboot flash via the Xiaomi Flash tool sufficient?

Kind regards,

Steve

**Comment by belzebub40k** [comment]
I faced a similar behaviour a while ago. After each flash I ended up in what looked like a boot loop but in the end it turned out to be something else. I was able to boot the regular system from within the recovery (twrp -> reboot to system) but after each flash I was stuck again. I tried everything from complete wipes to restoring stock firmware but nothing helped. In the end for me the fix was to reflash the latest twrp firmware via fastboot.

**Comment by penglezos** [comment]
> Hi!
> 
> Firstly a big thank you for doing this for the raphael - I'm excited to try it.
> 
> Sadly though I always seem to end up in TWRP (recovery) after flashing the LineageOS ROM
> 
> * Mi9T Pro
> * unlocked bootloader
> * fresh fastboot-flash of the latest MIUI12.5 global using the Xiaomi Flash tool
> 
> The readme states to wipe "Data/Cache/System/Vendor" - is that the case? I don't think I usually wipe all of those but I could be wrong. Also is it a requirement to flash "latest Android 11 firmware according to your region" from TWRP before applying the Lineage ROM - or is my fastboot flash via the Xiaomi Flash tool sufficient?
> 
> Kind regards,
> 
> Steve

Hey Steve,

Thanks for submitting your issue! Apparently it seems you came from MIUI official ROM which requires to format data and wipe internal storage too. Be aware you will loose all your data so back them up first. Rest installation instructions are given. In order to flash the firmware you can do it from twrp no need to sideload it through Mi flash tool.

Regards,

Panagiotis
